# Generated by Django 5.2.6 on 2025-10-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_canteen', '0007_alter_order_payment_method_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
