# Generated by Django 5.2.6 on 2025-10-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_canteen', '0008_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
